# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
    exclude: ".vscode"
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.246
  hooks:
    - id: ruff

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.950
  hooks:
  - id: mypy
    additional_dependencies:
    - types-python-dateutil
    - types-requests
